version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip

  pre_build:
    commands:
      - cd backend
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Build phase - nothing to compile"

  post_build:
    commands:
      - echo "Zipping for Elastic Beanstalk"
      - zip -r ../backend.zip ./*

artifacts:
  files:
    - backend.zip
